package com.shiti;
// Generated 2018-6-29 17:30:31 by Hibernate Tools 5.2.3.Final

/**
 * DbClass generated by hbm2java
 */
public class DbClass implements java.io.Serializable {

	private static final long serialVersionUID =1L;
	private int eclass;
	private int college;
	private String name;
	private Integer teacher;

	public DbClass() {
	}

	public DbClass(int eclass, int college, String name) {
		this.eclass = eclass;
		this.college = college;
		this.name = name;
	}

	public DbClass(int eclass, int college, String name, Integer teacher) {
		this.eclass = eclass;
		this.college = college;
		this.name = name;
		this.teacher = teacher;
	}

	public int getEclass() {
		return this.eclass;
	}

	public void setEclass(int eclass) {
		this.eclass = eclass;
	}

	public int getCollege() {
		return this.college;
	}

	public void setCollege(int college) {
		this.college = college;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Integer teacher) {
		this.teacher = teacher;
	}

}
