package com.shiti;
// Generated 2018-6-29 17:30:31 by Hibernate Tools 5.2.3.Final

/**
 * DbStudent generated by hbm2java
 */
public class DbStudent implements java.io.Serializable {

	private static final long serialVersionUID =1L;
	private int student;
	private String password;
	private String name;
	private String sex;
	private int college;
	private int eclass;

	public DbStudent() {
	}

	public DbStudent(int student, String password, String name, String sex, int college, int eclass) {
		this.student = student;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.college = college;
		this.eclass = eclass;
	}

	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public int getCollege() {
		return this.college;
	}

	public void setCollege(int college) {
		this.college = college;
	}

	public int getEclass() {
		return this.eclass;
	}

	public void setEclass(int eclass) {
		this.eclass = eclass;
	}

}
