package com.shiti;
// Generated 2018-6-29 17:30:31 by Hibernate Tools 5.2.3.Final

/**
 * DbTeacher generated by hbm2java
 */
public class DbTeacher implements java.io.Serializable {

	
	private static final long serialVersionUID =1L;
	private int teacher;
	private String password;
	private String name;
	private String sex;
	private int college;
	private int jurisdiction;

	public DbTeacher() {
	}

	public DbTeacher(int teacher, String password, String name, String sex, int college, int jurisdiction) {
		this.teacher = teacher;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.college = college;
		this.jurisdiction = jurisdiction;
	}

	public int getTeacher() {
		return this.teacher;
	}

	public void setTeacher(int teacher) {
		this.teacher = teacher;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public int getCollege() {
		return this.college;
	}

	public void setCollege(int college) {
		this.college = college;
	}

	public int getJurisdiction() {
		return this.jurisdiction;
	}

	public void setJurisdiction(int jurisdiction) {
		this.jurisdiction = jurisdiction;
	}

}
